# Generated by Django 6.0.4 on 2026-04-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('user_count', models.PositiveIntegerField(default=0, verbose_name='Новые пользователи')),
                ('event_count', models.PositiveIntegerField(default=0, verbose_name='Создано событий')),
                ('edited_events', models.PositiveIntegerField(default=0, verbose_name='Отредактировано событий')),
                ('cancelled_events', models.PositiveIntegerField(default=0, verbose_name='Отменено событий')),
            ],
            options={
                'verbose_name': 'Статистика бота',
                'verbose_name_plural': 'Статистика бота',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
