# Generated by Django 6.0.4 on 2026-04-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Запланировано'), ('pending', 'Ожидание подтверждения'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=40),
        ),
    ]
