# Generated by Django 6.0.4 on 2026-04-14 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='events_cancelled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='events_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='events_edited',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
