# Generated by Django 6.0.4 on 2026-04-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_userprofile_events_cancelled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичное событие'),
        ),
    ]
